name: Dynamic Scan Using ZAP
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web Application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ewf: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          xmd_options: '-a'
